// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: whatevr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetStatus_FullMethodName       = "/whatevr.v1.DaemonService/GetStatus"
	DaemonService_SubscribeEvents_FullMethodName = "/whatevr.v1.DaemonService/SubscribeEvents"
	DaemonService_Reconnect_FullMethodName       = "/whatevr.v1.DaemonService/Reconnect"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonEvent], error)
	Reconnect(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (*ReconnectResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, DaemonEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_SubscribeEventsClient = grpc.ServerStreamingClient[DaemonEvent]

func (c *daemonServiceClient) Reconnect(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (*ReconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconnectResponse)
	err := c.cc.Invoke(ctx, DaemonService_Reconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[DaemonEvent]) error
	Reconnect(context.Context, *ReconnectRequest) (*ReconnectResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[DaemonEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedDaemonServiceServer) Reconnect(context.Context, *ReconnectRequest) (*ReconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconnect not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, DaemonEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_SubscribeEventsServer = grpc.ServerStreamingServer[DaemonEvent]

func _DaemonService_Reconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Reconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Reconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Reconnect(ctx, req.(*ReconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
		{
			MethodName: "Reconnect",
			Handler:    _DaemonService_Reconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _DaemonService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "whatevr.proto",
}

const (
	LoginService_SubscribeLoginEvents_FullMethodName = "/whatevr.v1.LoginService/SubscribeLoginEvents"
	LoginService_Logout_FullMethodName               = "/whatevr.v1.LoginService/Logout"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	SubscribeLoginEvents(ctx context.Context, in *SubscribeLoginEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginEvent], error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) SubscribeLoginEvents(ctx context.Context, in *SubscribeLoginEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoginService_ServiceDesc.Streams[0], LoginService_SubscribeLoginEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeLoginEventsRequest, LoginEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoginService_SubscribeLoginEventsClient = grpc.ServerStreamingClient[LoginEvent]

func (c *loginServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, LoginService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	SubscribeLoginEvents(*SubscribeLoginEventsRequest, grpc.ServerStreamingServer[LoginEvent]) error
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) SubscribeLoginEvents(*SubscribeLoginEventsRequest, grpc.ServerStreamingServer[LoginEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeLoginEvents not implemented")
}
func (UnimplementedLoginServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call panics, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_SubscribeLoginEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLoginEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoginServiceServer).SubscribeLoginEvents(m, &grpc.GenericServerStream[SubscribeLoginEventsRequest, LoginEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoginService_SubscribeLoginEventsServer = grpc.ServerStreamingServer[LoginEvent]

func _LoginService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Logout",
			Handler:    _LoginService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeLoginEvents",
			Handler:       _LoginService_SubscribeLoginEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "whatevr.proto",
}

const (
	FrontendService_HoldSession_FullMethodName        = "/whatevr.v1.FrontendService/HoldSession"
	FrontendService_UpdateSessionState_FullMethodName = "/whatevr.v1.FrontendService/UpdateSessionState"
)

// FrontendServiceClient is the client API for FrontendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendServiceClient interface {
	HoldSession(ctx context.Context, in *HoldSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrontendSessionEvent], error)
	UpdateSessionState(ctx context.Context, in *UpdateSessionStateRequest, opts ...grpc.CallOption) (*UpdateSessionStateResponse, error)
}

type frontendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendServiceClient(cc grpc.ClientConnInterface) FrontendServiceClient {
	return &frontendServiceClient{cc}
}

func (c *frontendServiceClient) HoldSession(ctx context.Context, in *HoldSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FrontendSessionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FrontendService_ServiceDesc.Streams[0], FrontendService_HoldSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HoldSessionRequest, FrontendSessionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrontendService_HoldSessionClient = grpc.ServerStreamingClient[FrontendSessionEvent]

func (c *frontendServiceClient) UpdateSessionState(ctx context.Context, in *UpdateSessionStateRequest, opts ...grpc.CallOption) (*UpdateSessionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionStateResponse)
	err := c.cc.Invoke(ctx, FrontendService_UpdateSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontendServiceServer is the server API for FrontendService service.
// All implementations must embed UnimplementedFrontendServiceServer
// for forward compatibility.
type FrontendServiceServer interface {
	HoldSession(*HoldSessionRequest, grpc.ServerStreamingServer[FrontendSessionEvent]) error
	UpdateSessionState(context.Context, *UpdateSessionStateRequest) (*UpdateSessionStateResponse, error)
	mustEmbedUnimplementedFrontendServiceServer()
}

// UnimplementedFrontendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontendServiceServer struct{}

func (UnimplementedFrontendServiceServer) HoldSession(*HoldSessionRequest, grpc.ServerStreamingServer[FrontendSessionEvent]) error {
	return status.Error(codes.Unimplemented, "method HoldSession not implemented")
}
func (UnimplementedFrontendServiceServer) UpdateSessionState(context.Context, *UpdateSessionStateRequest) (*UpdateSessionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSessionState not implemented")
}
func (UnimplementedFrontendServiceServer) mustEmbedUnimplementedFrontendServiceServer() {}
func (UnimplementedFrontendServiceServer) testEmbeddedByValue()                         {}

// UnsafeFrontendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServiceServer will
// result in compilation errors.
type UnsafeFrontendServiceServer interface {
	mustEmbedUnimplementedFrontendServiceServer()
}

func RegisterFrontendServiceServer(s grpc.ServiceRegistrar, srv FrontendServiceServer) {
	// If the following call panics, it indicates UnimplementedFrontendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrontendService_ServiceDesc, srv)
}

func _FrontendService_HoldSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HoldSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontendServiceServer).HoldSession(m, &grpc.GenericServerStream[HoldSessionRequest, FrontendSessionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrontendService_HoldSessionServer = grpc.ServerStreamingServer[FrontendSessionEvent]

func _FrontendService_UpdateSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).UpdateSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_UpdateSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).UpdateSessionState(ctx, req.(*UpdateSessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontendService_ServiceDesc is the grpc.ServiceDesc for FrontendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.FrontendService",
	HandlerType: (*FrontendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSessionState",
			Handler:    _FrontendService_UpdateSessionState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HoldSession",
			Handler:       _FrontendService_HoldSession_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "whatevr.proto",
}

const (
	ChatService_ListChats_FullMethodName             = "/whatevr.v1.ChatService/ListChats"
	ChatService_GetMessages_FullMethodName           = "/whatevr.v1.ChatService/GetMessages"
	ChatService_MarkChatRead_FullMethodName          = "/whatevr.v1.ChatService/MarkChatRead"
	ChatService_SetChatPinned_FullMethodName         = "/whatevr.v1.ChatService/SetChatPinned"
	ChatService_SetChatPresence_FullMethodName       = "/whatevr.v1.ChatService/SetChatPresence"
	ChatService_SubscribeChatPresence_FullMethodName = "/whatevr.v1.ChatService/SubscribeChatPresence"
	ChatService_DownloadMessageMedia_FullMethodName  = "/whatevr.v1.ChatService/DownloadMessageMedia"
	ChatService_GetMessageInfo_FullMethodName        = "/whatevr.v1.ChatService/GetMessageInfo"
	ChatService_DeleteMessageForMe_FullMethodName    = "/whatevr.v1.ChatService/DeleteMessageForMe"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	MarkChatRead(ctx context.Context, in *MarkChatReadRequest, opts ...grpc.CallOption) (*MarkChatReadResponse, error)
	SetChatPinned(ctx context.Context, in *SetChatPinnedRequest, opts ...grpc.CallOption) (*SetChatPinnedResponse, error)
	SetChatPresence(ctx context.Context, in *SetChatPresenceRequest, opts ...grpc.CallOption) (*SetChatPresenceResponse, error)
	SubscribeChatPresence(ctx context.Context, in *SubscribeChatPresenceRequest, opts ...grpc.CallOption) (*SubscribeChatPresenceResponse, error)
	DownloadMessageMedia(ctx context.Context, in *DownloadMessageMediaRequest, opts ...grpc.CallOption) (*DownloadMessageMediaResponse, error)
	GetMessageInfo(ctx context.Context, in *GetMessageInfoRequest, opts ...grpc.CallOption) (*GetMessageInfoResponse, error)
	DeleteMessageForMe(ctx context.Context, in *DeleteMessageForMeRequest, opts ...grpc.CallOption) (*DeleteMessageForMeResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, ChatService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MarkChatRead(ctx context.Context, in *MarkChatReadRequest, opts ...grpc.CallOption) (*MarkChatReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkChatReadResponse)
	err := c.cc.Invoke(ctx, ChatService_MarkChatRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetChatPinned(ctx context.Context, in *SetChatPinnedRequest, opts ...grpc.CallOption) (*SetChatPinnedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetChatPinnedResponse)
	err := c.cc.Invoke(ctx, ChatService_SetChatPinned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetChatPresence(ctx context.Context, in *SetChatPresenceRequest, opts ...grpc.CallOption) (*SetChatPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetChatPresenceResponse)
	err := c.cc.Invoke(ctx, ChatService_SetChatPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SubscribeChatPresence(ctx context.Context, in *SubscribeChatPresenceRequest, opts ...grpc.CallOption) (*SubscribeChatPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeChatPresenceResponse)
	err := c.cc.Invoke(ctx, ChatService_SubscribeChatPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DownloadMessageMedia(ctx context.Context, in *DownloadMessageMediaRequest, opts ...grpc.CallOption) (*DownloadMessageMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadMessageMediaResponse)
	err := c.cc.Invoke(ctx, ChatService_DownloadMessageMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessageInfo(ctx context.Context, in *GetMessageInfoRequest, opts ...grpc.CallOption) (*GetMessageInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageInfoResponse)
	err := c.cc.Invoke(ctx, ChatService_GetMessageInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteMessageForMe(ctx context.Context, in *DeleteMessageForMeRequest, opts ...grpc.CallOption) (*DeleteMessageForMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageForMeResponse)
	err := c.cc.Invoke(ctx, ChatService_DeleteMessageForMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	MarkChatRead(context.Context, *MarkChatReadRequest) (*MarkChatReadResponse, error)
	SetChatPinned(context.Context, *SetChatPinnedRequest) (*SetChatPinnedResponse, error)
	SetChatPresence(context.Context, *SetChatPresenceRequest) (*SetChatPresenceResponse, error)
	SubscribeChatPresence(context.Context, *SubscribeChatPresenceRequest) (*SubscribeChatPresenceResponse, error)
	DownloadMessageMedia(context.Context, *DownloadMessageMediaRequest) (*DownloadMessageMediaResponse, error)
	GetMessageInfo(context.Context, *GetMessageInfoRequest) (*GetMessageInfoResponse, error)
	DeleteMessageForMe(context.Context, *DeleteMessageForMeRequest) (*DeleteMessageForMeResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedChatServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedChatServiceServer) MarkChatRead(context.Context, *MarkChatReadRequest) (*MarkChatReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkChatRead not implemented")
}
func (UnimplementedChatServiceServer) SetChatPinned(context.Context, *SetChatPinnedRequest) (*SetChatPinnedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetChatPinned not implemented")
}
func (UnimplementedChatServiceServer) SetChatPresence(context.Context, *SetChatPresenceRequest) (*SetChatPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetChatPresence not implemented")
}
func (UnimplementedChatServiceServer) SubscribeChatPresence(context.Context, *SubscribeChatPresenceRequest) (*SubscribeChatPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeChatPresence not implemented")
}
func (UnimplementedChatServiceServer) DownloadMessageMedia(context.Context, *DownloadMessageMediaRequest) (*DownloadMessageMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadMessageMedia not implemented")
}
func (UnimplementedChatServiceServer) GetMessageInfo(context.Context, *GetMessageInfoRequest) (*GetMessageInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageInfo not implemented")
}
func (UnimplementedChatServiceServer) DeleteMessageForMe(context.Context, *DeleteMessageForMeRequest) (*DeleteMessageForMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessageForMe not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListChats(ctx, req.(*ListChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MarkChatRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkChatReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MarkChatRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MarkChatRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MarkChatRead(ctx, req.(*MarkChatReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetChatPinned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChatPinnedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetChatPinned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetChatPinned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetChatPinned(ctx, req.(*SetChatPinnedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetChatPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChatPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetChatPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetChatPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetChatPresence(ctx, req.(*SetChatPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SubscribeChatPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeChatPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SubscribeChatPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SubscribeChatPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SubscribeChatPresence(ctx, req.(*SubscribeChatPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DownloadMessageMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadMessageMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DownloadMessageMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DownloadMessageMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DownloadMessageMedia(ctx, req.(*DownloadMessageMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetMessageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessageInfo(ctx, req.(*GetMessageInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteMessageForMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageForMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteMessageForMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteMessageForMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteMessageForMe(ctx, req.(*DeleteMessageForMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChats",
			Handler:    _ChatService_ListChats_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
		{
			MethodName: "MarkChatRead",
			Handler:    _ChatService_MarkChatRead_Handler,
		},
		{
			MethodName: "SetChatPinned",
			Handler:    _ChatService_SetChatPinned_Handler,
		},
		{
			MethodName: "SetChatPresence",
			Handler:    _ChatService_SetChatPresence_Handler,
		},
		{
			MethodName: "SubscribeChatPresence",
			Handler:    _ChatService_SubscribeChatPresence_Handler,
		},
		{
			MethodName: "DownloadMessageMedia",
			Handler:    _ChatService_DownloadMessageMedia_Handler,
		},
		{
			MethodName: "GetMessageInfo",
			Handler:    _ChatService_GetMessageInfo_Handler,
		},
		{
			MethodName: "DeleteMessageForMe",
			Handler:    _ChatService_DeleteMessageForMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whatevr.proto",
}

const (
	SendService_SendText_FullMethodName       = "/whatevr.v1.SendService/SendText"
	SendService_SendMedia_FullMethodName      = "/whatevr.v1.SendService/SendMedia"
	SendService_RevokeMessage_FullMethodName  = "/whatevr.v1.SendService/RevokeMessage"
	SendService_ForwardMessage_FullMethodName = "/whatevr.v1.SendService/ForwardMessage"
	SendService_SendReaction_FullMethodName   = "/whatevr.v1.SendService/SendReaction"
)

// SendServiceClient is the client API for SendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendServiceClient interface {
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error)
	SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error)
	RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error)
	ForwardMessage(ctx context.Context, in *ForwardMessageRequest, opts ...grpc.CallOption) (*ForwardMessageResponse, error)
	SendReaction(ctx context.Context, in *SendReactionRequest, opts ...grpc.CallOption) (*SendReactionResponse, error)
}

type sendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendServiceClient(cc grpc.ClientConnInterface) SendServiceClient {
	return &sendServiceClient{cc}
}

func (c *sendServiceClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTextResponse)
	err := c.cc.Invoke(ctx, SendService_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendServiceClient) SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMediaResponse)
	err := c.cc.Invoke(ctx, SendService_SendMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendServiceClient) RevokeMessage(ctx context.Context, in *RevokeMessageRequest, opts ...grpc.CallOption) (*RevokeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMessageResponse)
	err := c.cc.Invoke(ctx, SendService_RevokeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendServiceClient) ForwardMessage(ctx context.Context, in *ForwardMessageRequest, opts ...grpc.CallOption) (*ForwardMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardMessageResponse)
	err := c.cc.Invoke(ctx, SendService_ForwardMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendServiceClient) SendReaction(ctx context.Context, in *SendReactionRequest, opts ...grpc.CallOption) (*SendReactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReactionResponse)
	err := c.cc.Invoke(ctx, SendService_SendReaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendServiceServer is the server API for SendService service.
// All implementations must embed UnimplementedSendServiceServer
// for forward compatibility.
type SendServiceServer interface {
	SendText(context.Context, *SendTextRequest) (*SendTextResponse, error)
	SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error)
	RevokeMessage(context.Context, *RevokeMessageRequest) (*RevokeMessageResponse, error)
	ForwardMessage(context.Context, *ForwardMessageRequest) (*ForwardMessageResponse, error)
	SendReaction(context.Context, *SendReactionRequest) (*SendReactionResponse, error)
	mustEmbedUnimplementedSendServiceServer()
}

// UnimplementedSendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendServiceServer struct{}

func (UnimplementedSendServiceServer) SendText(context.Context, *SendTextRequest) (*SendTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedSendServiceServer) SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMedia not implemented")
}
func (UnimplementedSendServiceServer) RevokeMessage(context.Context, *RevokeMessageRequest) (*RevokeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMessage not implemented")
}
func (UnimplementedSendServiceServer) ForwardMessage(context.Context, *ForwardMessageRequest) (*ForwardMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardMessage not implemented")
}
func (UnimplementedSendServiceServer) SendReaction(context.Context, *SendReactionRequest) (*SendReactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReaction not implemented")
}
func (UnimplementedSendServiceServer) mustEmbedUnimplementedSendServiceServer() {}
func (UnimplementedSendServiceServer) testEmbeddedByValue()                     {}

// UnsafeSendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendServiceServer will
// result in compilation errors.
type UnsafeSendServiceServer interface {
	mustEmbedUnimplementedSendServiceServer()
}

func RegisterSendServiceServer(s grpc.ServiceRegistrar, srv SendServiceServer) {
	// If the following call panics, it indicates UnimplementedSendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SendService_ServiceDesc, srv)
}

func _SendService_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendService_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendService_SendMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).SendMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendService_SendMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).SendMedia(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendService_RevokeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).RevokeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendService_RevokeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).RevokeMessage(ctx, req.(*RevokeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendService_ForwardMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).ForwardMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendService_ForwardMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).ForwardMessage(ctx, req.(*ForwardMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendService_SendReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServiceServer).SendReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendService_SendReaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServiceServer).SendReaction(ctx, req.(*SendReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SendService_ServiceDesc is the grpc.ServiceDesc for SendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.SendService",
	HandlerType: (*SendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendText",
			Handler:    _SendService_SendText_Handler,
		},
		{
			MethodName: "SendMedia",
			Handler:    _SendService_SendMedia_Handler,
		},
		{
			MethodName: "RevokeMessage",
			Handler:    _SendService_RevokeMessage_Handler,
		},
		{
			MethodName: "ForwardMessage",
			Handler:    _SendService_ForwardMessage_Handler,
		},
		{
			MethodName: "SendReaction",
			Handler:    _SendService_SendReaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whatevr.proto",
}

const (
	StickerService_ListStickers_FullMethodName            = "/whatevr.v1.StickerService/ListStickers"
	StickerService_ListStickerPacks_FullMethodName        = "/whatevr.v1.StickerService/ListStickerPacks"
	StickerService_GetStickerPack_FullMethodName          = "/whatevr.v1.StickerService/GetStickerPack"
	StickerService_DownloadSticker_FullMethodName         = "/whatevr.v1.StickerService/DownloadSticker"
	StickerService_SetStickerPackInstalled_FullMethodName = "/whatevr.v1.StickerService/SetStickerPackInstalled"
	StickerService_SendSticker_FullMethodName             = "/whatevr.v1.StickerService/SendSticker"
	StickerService_SetStickerFavorite_FullMethodName      = "/whatevr.v1.StickerService/SetStickerFavorite"
)

// StickerServiceClient is the client API for StickerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StickerServiceClient interface {
	ListStickers(ctx context.Context, in *ListStickersRequest, opts ...grpc.CallOption) (*ListStickersResponse, error)
	ListStickerPacks(ctx context.Context, in *ListStickerPacksRequest, opts ...grpc.CallOption) (*ListStickerPacksResponse, error)
	GetStickerPack(ctx context.Context, in *GetStickerPackRequest, opts ...grpc.CallOption) (*GetStickerPackResponse, error)
	DownloadSticker(ctx context.Context, in *DownloadStickerRequest, opts ...grpc.CallOption) (*DownloadStickerResponse, error)
	SetStickerPackInstalled(ctx context.Context, in *SetStickerPackInstalledRequest, opts ...grpc.CallOption) (*SetStickerPackInstalledResponse, error)
	SendSticker(ctx context.Context, in *SendStickerRequest, opts ...grpc.CallOption) (*SendStickerResponse, error)
	SetStickerFavorite(ctx context.Context, in *SetStickerFavoriteRequest, opts ...grpc.CallOption) (*SetStickerFavoriteResponse, error)
}

type stickerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStickerServiceClient(cc grpc.ClientConnInterface) StickerServiceClient {
	return &stickerServiceClient{cc}
}

func (c *stickerServiceClient) ListStickers(ctx context.Context, in *ListStickersRequest, opts ...grpc.CallOption) (*ListStickersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStickersResponse)
	err := c.cc.Invoke(ctx, StickerService_ListStickers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) ListStickerPacks(ctx context.Context, in *ListStickerPacksRequest, opts ...grpc.CallOption) (*ListStickerPacksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStickerPacksResponse)
	err := c.cc.Invoke(ctx, StickerService_ListStickerPacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) GetStickerPack(ctx context.Context, in *GetStickerPackRequest, opts ...grpc.CallOption) (*GetStickerPackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStickerPackResponse)
	err := c.cc.Invoke(ctx, StickerService_GetStickerPack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) DownloadSticker(ctx context.Context, in *DownloadStickerRequest, opts ...grpc.CallOption) (*DownloadStickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadStickerResponse)
	err := c.cc.Invoke(ctx, StickerService_DownloadSticker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) SetStickerPackInstalled(ctx context.Context, in *SetStickerPackInstalledRequest, opts ...grpc.CallOption) (*SetStickerPackInstalledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStickerPackInstalledResponse)
	err := c.cc.Invoke(ctx, StickerService_SetStickerPackInstalled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) SendSticker(ctx context.Context, in *SendStickerRequest, opts ...grpc.CallOption) (*SendStickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStickerResponse)
	err := c.cc.Invoke(ctx, StickerService_SendSticker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stickerServiceClient) SetStickerFavorite(ctx context.Context, in *SetStickerFavoriteRequest, opts ...grpc.CallOption) (*SetStickerFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStickerFavoriteResponse)
	err := c.cc.Invoke(ctx, StickerService_SetStickerFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StickerServiceServer is the server API for StickerService service.
// All implementations must embed UnimplementedStickerServiceServer
// for forward compatibility.
type StickerServiceServer interface {
	ListStickers(context.Context, *ListStickersRequest) (*ListStickersResponse, error)
	ListStickerPacks(context.Context, *ListStickerPacksRequest) (*ListStickerPacksResponse, error)
	GetStickerPack(context.Context, *GetStickerPackRequest) (*GetStickerPackResponse, error)
	DownloadSticker(context.Context, *DownloadStickerRequest) (*DownloadStickerResponse, error)
	SetStickerPackInstalled(context.Context, *SetStickerPackInstalledRequest) (*SetStickerPackInstalledResponse, error)
	SendSticker(context.Context, *SendStickerRequest) (*SendStickerResponse, error)
	SetStickerFavorite(context.Context, *SetStickerFavoriteRequest) (*SetStickerFavoriteResponse, error)
	mustEmbedUnimplementedStickerServiceServer()
}

// UnimplementedStickerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStickerServiceServer struct{}

func (UnimplementedStickerServiceServer) ListStickers(context.Context, *ListStickersRequest) (*ListStickersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStickers not implemented")
}
func (UnimplementedStickerServiceServer) ListStickerPacks(context.Context, *ListStickerPacksRequest) (*ListStickerPacksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStickerPacks not implemented")
}
func (UnimplementedStickerServiceServer) GetStickerPack(context.Context, *GetStickerPackRequest) (*GetStickerPackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStickerPack not implemented")
}
func (UnimplementedStickerServiceServer) DownloadSticker(context.Context, *DownloadStickerRequest) (*DownloadStickerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadSticker not implemented")
}
func (UnimplementedStickerServiceServer) SetStickerPackInstalled(context.Context, *SetStickerPackInstalledRequest) (*SetStickerPackInstalledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStickerPackInstalled not implemented")
}
func (UnimplementedStickerServiceServer) SendSticker(context.Context, *SendStickerRequest) (*SendStickerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSticker not implemented")
}
func (UnimplementedStickerServiceServer) SetStickerFavorite(context.Context, *SetStickerFavoriteRequest) (*SetStickerFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStickerFavorite not implemented")
}
func (UnimplementedStickerServiceServer) mustEmbedUnimplementedStickerServiceServer() {}
func (UnimplementedStickerServiceServer) testEmbeddedByValue()                        {}

// UnsafeStickerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StickerServiceServer will
// result in compilation errors.
type UnsafeStickerServiceServer interface {
	mustEmbedUnimplementedStickerServiceServer()
}

func RegisterStickerServiceServer(s grpc.ServiceRegistrar, srv StickerServiceServer) {
	// If the following call panics, it indicates UnimplementedStickerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StickerService_ServiceDesc, srv)
}

func _StickerService_ListStickers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStickersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).ListStickers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_ListStickers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).ListStickers(ctx, req.(*ListStickersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_ListStickerPacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStickerPacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).ListStickerPacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_ListStickerPacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).ListStickerPacks(ctx, req.(*ListStickerPacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_GetStickerPack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStickerPackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).GetStickerPack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_GetStickerPack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).GetStickerPack(ctx, req.(*GetStickerPackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_DownloadSticker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadStickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).DownloadSticker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_DownloadSticker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).DownloadSticker(ctx, req.(*DownloadStickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_SetStickerPackInstalled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStickerPackInstalledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).SetStickerPackInstalled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_SetStickerPackInstalled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).SetStickerPackInstalled(ctx, req.(*SetStickerPackInstalledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_SendSticker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).SendSticker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_SendSticker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).SendSticker(ctx, req.(*SendStickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StickerService_SetStickerFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStickerFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StickerServiceServer).SetStickerFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StickerService_SetStickerFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StickerServiceServer).SetStickerFavorite(ctx, req.(*SetStickerFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StickerService_ServiceDesc is the grpc.ServiceDesc for StickerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StickerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatevr.v1.StickerService",
	HandlerType: (*StickerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStickers",
			Handler:    _StickerService_ListStickers_Handler,
		},
		{
			MethodName: "ListStickerPacks",
			Handler:    _StickerService_ListStickerPacks_Handler,
		},
		{
			MethodName: "GetStickerPack",
			Handler:    _StickerService_GetStickerPack_Handler,
		},
		{
			MethodName: "DownloadSticker",
			Handler:    _StickerService_DownloadSticker_Handler,
		},
		{
			MethodName: "SetStickerPackInstalled",
			Handler:    _StickerService_SetStickerPackInstalled_Handler,
		},
		{
			MethodName: "SendSticker",
			Handler:    _StickerService_SendSticker_Handler,
		},
		{
			MethodName: "SetStickerFavorite",
			Handler:    _StickerService_SetStickerFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whatevr.proto",
}
