// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/whatevr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonState int32

const (
	DaemonState_DAEMON_STATE_UNSPECIFIED  DaemonState = 0
	DaemonState_DAEMON_STATE_STARTING     DaemonState = 1
	DaemonState_DAEMON_STATE_NEED_LOGIN   DaemonState = 2
	DaemonState_DAEMON_STATE_CONNECTING   DaemonState = 3
	DaemonState_DAEMON_STATE_ONLINE       DaemonState = 4
	DaemonState_DAEMON_STATE_RECONNECTING DaemonState = 5
	DaemonState_DAEMON_STATE_OFFLINE      DaemonState = 6
)

// Enum value maps for DaemonState.
var (
	DaemonState_name = map[int32]string{
		0: "DAEMON_STATE_UNSPECIFIED",
		1: "DAEMON_STATE_STARTING",
		2: "DAEMON_STATE_NEED_LOGIN",
		3: "DAEMON_STATE_CONNECTING",
		4: "DAEMON_STATE_ONLINE",
		5: "DAEMON_STATE_RECONNECTING",
		6: "DAEMON_STATE_OFFLINE",
	}
	DaemonState_value = map[string]int32{
		"DAEMON_STATE_UNSPECIFIED":  0,
		"DAEMON_STATE_STARTING":     1,
		"DAEMON_STATE_NEED_LOGIN":   2,
		"DAEMON_STATE_CONNECTING":   3,
		"DAEMON_STATE_ONLINE":       4,
		"DAEMON_STATE_RECONNECTING": 5,
		"DAEMON_STATE_OFFLINE":      6,
	}
)

func (x DaemonState) Enum() *DaemonState {
	p := new(DaemonState)
	*p = x
	return p
}

func (x DaemonState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_whatevr_proto_enumTypes[0].Descriptor()
}

func (DaemonState) Type() protoreflect.EnumType {
	return &file_proto_whatevr_proto_enumTypes[0]
}

func (x DaemonState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonState.Descriptor instead.
func (DaemonState) EnumDescriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{0}
}

type MessageDirection int32

const (
	MessageDirection_MESSAGE_DIRECTION_UNSPECIFIED MessageDirection = 0
	MessageDirection_MESSAGE_DIRECTION_INCOMING    MessageDirection = 1
	MessageDirection_MESSAGE_DIRECTION_OUTGOING    MessageDirection = 2
)

// Enum value maps for MessageDirection.
var (
	MessageDirection_name = map[int32]string{
		0: "MESSAGE_DIRECTION_UNSPECIFIED",
		1: "MESSAGE_DIRECTION_INCOMING",
		2: "MESSAGE_DIRECTION_OUTGOING",
	}
	MessageDirection_value = map[string]int32{
		"MESSAGE_DIRECTION_UNSPECIFIED": 0,
		"MESSAGE_DIRECTION_INCOMING":    1,
		"MESSAGE_DIRECTION_OUTGOING":    2,
	}
)

func (x MessageDirection) Enum() *MessageDirection {
	p := new(MessageDirection)
	*p = x
	return p
}

func (x MessageDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_whatevr_proto_enumTypes[1].Descriptor()
}

func (MessageDirection) Type() protoreflect.EnumType {
	return &file_proto_whatevr_proto_enumTypes[1]
}

func (x MessageDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageDirection.Descriptor instead.
func (MessageDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{1}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_SENT",
		3: "MESSAGE_STATUS_DELIVERED",
		4: "MESSAGE_STATUS_READ",
		5: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_PENDING":     1,
		"MESSAGE_STATUS_SENT":        2,
		"MESSAGE_STATUS_DELIVERED":   3,
		"MESSAGE_STATUS_READ":        4,
		"MESSAGE_STATUS_FAILED":      5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_whatevr_proto_enumTypes[2].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_proto_whatevr_proto_enumTypes[2]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{2}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         DaemonState            `protobuf:"varint,1,opt,name=state,proto3,enum=whatevr.v1.DaemonState" json:"state,omitempty"`
	StateLabel    string                 `protobuf:"bytes,2,opt,name=state_label,json=stateLabel,proto3" json:"state_label,omitempty"`
	SocketPath    string                 `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	DataDir       string                 `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	CacheDir      string                 `protobuf:"bytes,5,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	DatabasePath  string                 `protobuf:"bytes,6,opt,name=database_path,json=databasePath,proto3" json:"database_path,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetState() DaemonState {
	if x != nil {
		return x.State
	}
	return DaemonState_DAEMON_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetStateLabel() string {
	if x != nil {
		return x.StateLabel
	}
	return ""
}

func (x *GetStatusResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *GetStatusResponse) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *GetStatusResponse) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *GetStatusResponse) GetDatabasePath() string {
	if x != nil {
		return x.DatabasePath
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{2}
}

type DaemonEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DaemonEvent_ConnectionChanged
	//	*DaemonEvent_LoginStateChanged
	//	*DaemonEvent_NewMessage
	//	*DaemonEvent_MessageUpdated
	//	*DaemonEvent_ChatUpdated
	Payload       isDaemonEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonEvent) Reset() {
	*x = DaemonEvent{}
	mi := &file_proto_whatevr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonEvent) ProtoMessage() {}

func (x *DaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonEvent.ProtoReflect.Descriptor instead.
func (*DaemonEvent) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{3}
}

func (x *DaemonEvent) GetPayload() isDaemonEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DaemonEvent) GetConnectionChanged() *ConnectionChanged {
	if x != nil {
		if x, ok := x.Payload.(*DaemonEvent_ConnectionChanged); ok {
			return x.ConnectionChanged
		}
	}
	return nil
}

func (x *DaemonEvent) GetLoginStateChanged() *LoginStateChanged {
	if x != nil {
		if x, ok := x.Payload.(*DaemonEvent_LoginStateChanged); ok {
			return x.LoginStateChanged
		}
	}
	return nil
}

func (x *DaemonEvent) GetNewMessage() *NewMessage {
	if x != nil {
		if x, ok := x.Payload.(*DaemonEvent_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *DaemonEvent) GetMessageUpdated() *MessageUpdated {
	if x != nil {
		if x, ok := x.Payload.(*DaemonEvent_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *DaemonEvent) GetChatUpdated() *ChatUpdated {
	if x != nil {
		if x, ok := x.Payload.(*DaemonEvent_ChatUpdated); ok {
			return x.ChatUpdated
		}
	}
	return nil
}

type isDaemonEvent_Payload interface {
	isDaemonEvent_Payload()
}

type DaemonEvent_ConnectionChanged struct {
	ConnectionChanged *ConnectionChanged `protobuf:"bytes,1,opt,name=connection_changed,json=connectionChanged,proto3,oneof"`
}

type DaemonEvent_LoginStateChanged struct {
	LoginStateChanged *LoginStateChanged `protobuf:"bytes,2,opt,name=login_state_changed,json=loginStateChanged,proto3,oneof"`
}

type DaemonEvent_NewMessage struct {
	NewMessage *NewMessage `protobuf:"bytes,3,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type DaemonEvent_MessageUpdated struct {
	MessageUpdated *MessageUpdated `protobuf:"bytes,4,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type DaemonEvent_ChatUpdated struct {
	ChatUpdated *ChatUpdated `protobuf:"bytes,5,opt,name=chat_updated,json=chatUpdated,proto3,oneof"`
}

func (*DaemonEvent_ConnectionChanged) isDaemonEvent_Payload() {}

func (*DaemonEvent_LoginStateChanged) isDaemonEvent_Payload() {}

func (*DaemonEvent_NewMessage) isDaemonEvent_Payload() {}

func (*DaemonEvent_MessageUpdated) isDaemonEvent_Payload() {}

func (*DaemonEvent_ChatUpdated) isDaemonEvent_Payload() {}

type ConnectionChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         DaemonState            `protobuf:"varint,1,opt,name=state,proto3,enum=whatevr.v1.DaemonState" json:"state,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionChanged) Reset() {
	*x = ConnectionChanged{}
	mi := &file_proto_whatevr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionChanged) ProtoMessage() {}

func (x *ConnectionChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionChanged.ProtoReflect.Descriptor instead.
func (*ConnectionChanged) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionChanged) GetState() DaemonState {
	if x != nil {
		return x.State
	}
	return DaemonState_DAEMON_STATE_UNSPECIFIED
}

func (x *ConnectionChanged) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LoginStateChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         DaemonState            `protobuf:"varint,1,opt,name=state,proto3,enum=whatevr.v1.DaemonState" json:"state,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStateChanged) Reset() {
	*x = LoginStateChanged{}
	mi := &file_proto_whatevr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStateChanged) ProtoMessage() {}

func (x *LoginStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStateChanged.ProtoReflect.Descriptor instead.
func (*LoginStateChanged) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{5}
}

func (x *LoginStateChanged) GetState() DaemonState {
	if x != nil {
		return x.State
	}
	return DaemonState_DAEMON_STATE_UNSPECIFIED
}

func (x *LoginStateChanged) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type NewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessage) Reset() {
	*x = NewMessage{}
	mi := &file_proto_whatevr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessage) ProtoMessage() {}

func (x *NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessage.ProtoReflect.Descriptor instead.
func (*NewMessage) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{6}
}

func (x *NewMessage) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdated) Reset() {
	*x = MessageUpdated{}
	mi := &file_proto_whatevr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdated) ProtoMessage() {}

func (x *MessageUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdated.ProtoReflect.Descriptor instead.
func (*MessageUpdated) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{7}
}

func (x *MessageUpdated) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ChatUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUpdated) Reset() {
	*x = ChatUpdated{}
	mi := &file_proto_whatevr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdated) ProtoMessage() {}

func (x *ChatUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdated.ProtoReflect.Descriptor instead.
func (*ChatUpdated) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{8}
}

func (x *ChatUpdated) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type SubscribeLoginEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLoginEventsRequest) Reset() {
	*x = SubscribeLoginEventsRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLoginEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLoginEventsRequest) ProtoMessage() {}

func (x *SubscribeLoginEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLoginEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLoginEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{9}
}

type LoginEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LoginEvent_QrCode
	//	*LoginEvent_LoginStateChanged
	Payload       isLoginEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	mi := &file_proto_whatevr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{10}
}

func (x *LoginEvent) GetPayload() isLoginEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoginEvent) GetQrCode() *QrCode {
	if x != nil {
		if x, ok := x.Payload.(*LoginEvent_QrCode); ok {
			return x.QrCode
		}
	}
	return nil
}

func (x *LoginEvent) GetLoginStateChanged() *LoginStateChanged {
	if x != nil {
		if x, ok := x.Payload.(*LoginEvent_LoginStateChanged); ok {
			return x.LoginStateChanged
		}
	}
	return nil
}

type isLoginEvent_Payload interface {
	isLoginEvent_Payload()
}

type LoginEvent_QrCode struct {
	QrCode *QrCode `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3,oneof"`
}

type LoginEvent_LoginStateChanged struct {
	LoginStateChanged *LoginStateChanged `protobuf:"bytes,2,opt,name=login_state_changed,json=loginStateChanged,proto3,oneof"`
}

func (*LoginEvent_QrCode) isLoginEvent_Payload() {}

func (*LoginEvent_LoginStateChanged) isLoginEvent_Payload() {}

type QrCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QrCode) Reset() {
	*x = QrCode{}
	mi := &file_proto_whatevr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QrCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrCode) ProtoMessage() {}

func (x *QrCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrCode.ProtoReflect.Descriptor instead.
func (*QrCode) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{11}
}

func (x *QrCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QrCode) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{12}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{13}
}

type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{14}
}

func (x *ListChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{15}
}

func (x *ListChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type GetMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeMessageId string                 `protobuf:"bytes,3,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeMessageId() string {
	if x != nil {
		return x.BeforeMessageId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{17}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MarkChatReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatReadRequest) Reset() {
	*x = MarkChatReadRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadRequest) ProtoMessage() {}

func (x *MarkChatReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadRequest.ProtoReflect.Descriptor instead.
func (*MarkChatReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{18}
}

func (x *MarkChatReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type MarkChatReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatReadResponse) Reset() {
	*x = MarkChatReadResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadResponse) ProtoMessage() {}

func (x *MarkChatReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadResponse.ProtoReflect.Descriptor instead.
func (*MarkChatReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{19}
}

type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_proto_whatevr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{20}
}

func (x *SendTextRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextResponse) Reset() {
	*x = SendTextResponse{}
	mi := &file_proto_whatevr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextResponse) ProtoMessage() {}

func (x *SendTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextResponse.ProtoReflect.Descriptor instead.
func (*SendTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{21}
}

func (x *SendTextResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Chat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastMessage         string                 `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMessageTimeUnix int64                  `protobuf:"varint,4,opt,name=last_message_time_unix,json=lastMessageTimeUnix,proto3" json:"last_message_time_unix,omitempty"`
	UnreadCount         int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsGroup             bool                   `protobuf:"varint,6,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_proto_whatevr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{22}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Chat) GetLastMessageTimeUnix() int64 {
	if x != nil {
		return x.LastMessageTimeUnix
	}
	return 0
}

func (x *Chat) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Chat) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Direction     MessageDirection       `protobuf:"varint,6,opt,name=direction,proto3,enum=whatevr.v1.MessageDirection" json:"direction,omitempty"`
	Status        MessageStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=whatevr.v1.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_whatevr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatevr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_whatevr_proto_rawDescGZIP(), []int{23}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Message) GetDirection() MessageDirection {
	if x != nil {
		return x.Direction
	}
	return MessageDirection_MESSAGE_DIRECTION_UNSPECIFIED
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

var File_proto_whatevr_proto protoreflect.FileDescriptor

const file_proto_whatevr_proto_rawDesc = "" +
	"\n" +
	"\x13proto/whatevr.proto\x12\n" +
	"whatevr.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xfb\x01\n" +
	"\x11GetStatusResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.whatevr.v1.DaemonStateR\x05state\x12\x1f\n" +
	"\vstate_label\x18\x02 \x01(\tR\n" +
	"stateLabel\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\x12\x19\n" +
	"\bdata_dir\x18\x04 \x01(\tR\adataDir\x12\x1b\n" +
	"\tcache_dir\x18\x05 \x01(\tR\bcacheDir\x12#\n" +
	"\rdatabase_path\x18\x06 \x01(\tR\fdatabasePath\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\x18\n" +
	"\x16SubscribeEventsRequest\"\xf9\x02\n" +
	"\vDaemonEvent\x12N\n" +
	"\x12connection_changed\x18\x01 \x01(\v2\x1d.whatevr.v1.ConnectionChangedH\x00R\x11connectionChanged\x12O\n" +
	"\x13login_state_changed\x18\x02 \x01(\v2\x1d.whatevr.v1.LoginStateChangedH\x00R\x11loginStateChanged\x129\n" +
	"\vnew_message\x18\x03 \x01(\v2\x16.whatevr.v1.NewMessageH\x00R\n" +
	"newMessage\x12E\n" +
	"\x0fmessage_updated\x18\x04 \x01(\v2\x1a.whatevr.v1.MessageUpdatedH\x00R\x0emessageUpdated\x12<\n" +
	"\fchat_updated\x18\x05 \x01(\v2\x17.whatevr.v1.ChatUpdatedH\x00R\vchatUpdatedB\t\n" +
	"\apayload\"Z\n" +
	"\x11ConnectionChanged\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.whatevr.v1.DaemonStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"Z\n" +
	"\x11LoginStateChanged\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.whatevr.v1.DaemonStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\";\n" +
	"\n" +
	"NewMessage\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.whatevr.v1.MessageR\amessage\"?\n" +
	"\x0eMessageUpdated\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.whatevr.v1.MessageR\amessage\"3\n" +
	"\vChatUpdated\x12$\n" +
	"\x04chat\x18\x01 \x01(\v2\x10.whatevr.v1.ChatR\x04chat\"\x1d\n" +
	"\x1bSubscribeLoginEventsRequest\"\x97\x01\n" +
	"\n" +
	"LoginEvent\x12-\n" +
	"\aqr_code\x18\x01 \x01(\v2\x12.whatevr.v1.QrCodeH\x00R\x06qrCode\x12O\n" +
	"\x13login_state_changed\x18\x02 \x01(\v2\x1d.whatevr.v1.LoginStateChangedH\x00R\x11loginStateChangedB\t\n" +
	"\apayload\"D\n" +
	"\x06QrCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"@\n" +
	"\x10ListChatsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\";\n" +
	"\x11ListChatsResponse\x12&\n" +
	"\x05chats\x18\x01 \x03(\v2\x10.whatevr.v1.ChatR\x05chats\"o\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12*\n" +
	"\x11before_message_id\x18\x03 \x01(\tR\x0fbeforeMessageId\"F\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.whatevr.v1.MessageR\bmessages\".\n" +
	"\x13MarkChatReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\x16\n" +
	"\x14MarkChatReadResponse\">\n" +
	"\x0fSendTextRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"A\n" +
	"\x10SendTextResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.whatevr.v1.MessageR\amessage\"\xc0\x01\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\flast_message\x18\x03 \x01(\tR\vlastMessage\x123\n" +
	"\x16last_message_time_unix\x18\x04 \x01(\x03R\x13lastMessageTimeUnix\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\x12\x19\n" +
	"\bis_group\x18\x06 \x01(\bR\aisGroup\"\xf9\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12:\n" +
	"\tdirection\x18\x06 \x01(\x0e2\x1c.whatevr.v1.MessageDirectionR\tdirection\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.whatevr.v1.MessageStatusR\x06status*\xd2\x01\n" +
	"\vDaemonState\x12\x1c\n" +
	"\x18DAEMON_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DAEMON_STATE_STARTING\x10\x01\x12\x1b\n" +
	"\x17DAEMON_STATE_NEED_LOGIN\x10\x02\x12\x1b\n" +
	"\x17DAEMON_STATE_CONNECTING\x10\x03\x12\x17\n" +
	"\x13DAEMON_STATE_ONLINE\x10\x04\x12\x1d\n" +
	"\x19DAEMON_STATE_RECONNECTING\x10\x05\x12\x18\n" +
	"\x14DAEMON_STATE_OFFLINE\x10\x06*u\n" +
	"\x10MessageDirection\x12!\n" +
	"\x1dMESSAGE_DIRECTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMESSAGE_DIRECTION_INCOMING\x10\x01\x12\x1e\n" +
	"\x1aMESSAGE_DIRECTION_OUTGOING\x10\x02*\xb6\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x02\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x03\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x04\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x052\xab\x01\n" +
	"\rDaemonService\x12H\n" +
	"\tGetStatus\x12\x1c.whatevr.v1.GetStatusRequest\x1a\x1d.whatevr.v1.GetStatusResponse\x12P\n" +
	"\x0fSubscribeEvents\x12\".whatevr.v1.SubscribeEventsRequest\x1a\x17.whatevr.v1.DaemonEvent0\x012\xaa\x01\n" +
	"\fLoginService\x12Y\n" +
	"\x14SubscribeLoginEvents\x12'.whatevr.v1.SubscribeLoginEventsRequest\x1a\x16.whatevr.v1.LoginEvent0\x01\x12?\n" +
	"\x06Logout\x12\x19.whatevr.v1.LogoutRequest\x1a\x1a.whatevr.v1.LogoutResponse2\xfa\x01\n" +
	"\vChatService\x12H\n" +
	"\tListChats\x12\x1c.whatevr.v1.ListChatsRequest\x1a\x1d.whatevr.v1.ListChatsResponse\x12N\n" +
	"\vGetMessages\x12\x1e.whatevr.v1.GetMessagesRequest\x1a\x1f.whatevr.v1.GetMessagesResponse\x12Q\n" +
	"\fMarkChatRead\x12\x1f.whatevr.v1.MarkChatReadRequest\x1a .whatevr.v1.MarkChatReadResponse2T\n" +
	"\vSendService\x12E\n" +
	"\bSendText\x12\x1b.whatevr.v1.SendTextRequest\x1a\x1c.whatevr.v1.SendTextResponseB\x1dZ\x1bwhatevrd/internal/rpc/pb;pbb\x06proto3"

var (
	file_proto_whatevr_proto_rawDescOnce sync.Once
	file_proto_whatevr_proto_rawDescData []byte
)

func file_proto_whatevr_proto_rawDescGZIP() []byte {
	file_proto_whatevr_proto_rawDescOnce.Do(func() {
		file_proto_whatevr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whatevr_proto_rawDesc), len(file_proto_whatevr_proto_rawDesc)))
	})
	return file_proto_whatevr_proto_rawDescData
}

var file_proto_whatevr_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_whatevr_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_whatevr_proto_goTypes = []any{
	(DaemonState)(0),                    // 0: whatevr.v1.DaemonState
	(MessageDirection)(0),               // 1: whatevr.v1.MessageDirection
	(MessageStatus)(0),                  // 2: whatevr.v1.MessageStatus
	(*GetStatusRequest)(nil),            // 3: whatevr.v1.GetStatusRequest
	(*GetStatusResponse)(nil),           // 4: whatevr.v1.GetStatusResponse
	(*SubscribeEventsRequest)(nil),      // 5: whatevr.v1.SubscribeEventsRequest
	(*DaemonEvent)(nil),                 // 6: whatevr.v1.DaemonEvent
	(*ConnectionChanged)(nil),           // 7: whatevr.v1.ConnectionChanged
	(*LoginStateChanged)(nil),           // 8: whatevr.v1.LoginStateChanged
	(*NewMessage)(nil),                  // 9: whatevr.v1.NewMessage
	(*MessageUpdated)(nil),              // 10: whatevr.v1.MessageUpdated
	(*ChatUpdated)(nil),                 // 11: whatevr.v1.ChatUpdated
	(*SubscribeLoginEventsRequest)(nil), // 12: whatevr.v1.SubscribeLoginEventsRequest
	(*LoginEvent)(nil),                  // 13: whatevr.v1.LoginEvent
	(*QrCode)(nil),                      // 14: whatevr.v1.QrCode
	(*LogoutRequest)(nil),               // 15: whatevr.v1.LogoutRequest
	(*LogoutResponse)(nil),              // 16: whatevr.v1.LogoutResponse
	(*ListChatsRequest)(nil),            // 17: whatevr.v1.ListChatsRequest
	(*ListChatsResponse)(nil),           // 18: whatevr.v1.ListChatsResponse
	(*GetMessagesRequest)(nil),          // 19: whatevr.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),         // 20: whatevr.v1.GetMessagesResponse
	(*MarkChatReadRequest)(nil),         // 21: whatevr.v1.MarkChatReadRequest
	(*MarkChatReadResponse)(nil),        // 22: whatevr.v1.MarkChatReadResponse
	(*SendTextRequest)(nil),             // 23: whatevr.v1.SendTextRequest
	(*SendTextResponse)(nil),            // 24: whatevr.v1.SendTextResponse
	(*Chat)(nil),                        // 25: whatevr.v1.Chat
	(*Message)(nil),                     // 26: whatevr.v1.Message
}
var file_proto_whatevr_proto_depIdxs = []int32{
	0,  // 0: whatevr.v1.GetStatusResponse.state:type_name -> whatevr.v1.DaemonState
	7,  // 1: whatevr.v1.DaemonEvent.connection_changed:type_name -> whatevr.v1.ConnectionChanged
	8,  // 2: whatevr.v1.DaemonEvent.login_state_changed:type_name -> whatevr.v1.LoginStateChanged
	9,  // 3: whatevr.v1.DaemonEvent.new_message:type_name -> whatevr.v1.NewMessage
	10, // 4: whatevr.v1.DaemonEvent.message_updated:type_name -> whatevr.v1.MessageUpdated
	11, // 5: whatevr.v1.DaemonEvent.chat_updated:type_name -> whatevr.v1.ChatUpdated
	0,  // 6: whatevr.v1.ConnectionChanged.state:type_name -> whatevr.v1.DaemonState
	0,  // 7: whatevr.v1.LoginStateChanged.state:type_name -> whatevr.v1.DaemonState
	26, // 8: whatevr.v1.NewMessage.message:type_name -> whatevr.v1.Message
	26, // 9: whatevr.v1.MessageUpdated.message:type_name -> whatevr.v1.Message
	25, // 10: whatevr.v1.ChatUpdated.chat:type_name -> whatevr.v1.Chat
	14, // 11: whatevr.v1.LoginEvent.qr_code:type_name -> whatevr.v1.QrCode
	8,  // 12: whatevr.v1.LoginEvent.login_state_changed:type_name -> whatevr.v1.LoginStateChanged
	25, // 13: whatevr.v1.ListChatsResponse.chats:type_name -> whatevr.v1.Chat
	26, // 14: whatevr.v1.GetMessagesResponse.messages:type_name -> whatevr.v1.Message
	26, // 15: whatevr.v1.SendTextResponse.message:type_name -> whatevr.v1.Message
	1,  // 16: whatevr.v1.Message.direction:type_name -> whatevr.v1.MessageDirection
	2,  // 17: whatevr.v1.Message.status:type_name -> whatevr.v1.MessageStatus
	3,  // 18: whatevr.v1.DaemonService.GetStatus:input_type -> whatevr.v1.GetStatusRequest
	5,  // 19: whatevr.v1.DaemonService.SubscribeEvents:input_type -> whatevr.v1.SubscribeEventsRequest
	12, // 20: whatevr.v1.LoginService.SubscribeLoginEvents:input_type -> whatevr.v1.SubscribeLoginEventsRequest
	15, // 21: whatevr.v1.LoginService.Logout:input_type -> whatevr.v1.LogoutRequest
	17, // 22: whatevr.v1.ChatService.ListChats:input_type -> whatevr.v1.ListChatsRequest
	19, // 23: whatevr.v1.ChatService.GetMessages:input_type -> whatevr.v1.GetMessagesRequest
	21, // 24: whatevr.v1.ChatService.MarkChatRead:input_type -> whatevr.v1.MarkChatReadRequest
	23, // 25: whatevr.v1.SendService.SendText:input_type -> whatevr.v1.SendTextRequest
	4,  // 26: whatevr.v1.DaemonService.GetStatus:output_type -> whatevr.v1.GetStatusResponse
	6,  // 27: whatevr.v1.DaemonService.SubscribeEvents:output_type -> whatevr.v1.DaemonEvent
	13, // 28: whatevr.v1.LoginService.SubscribeLoginEvents:output_type -> whatevr.v1.LoginEvent
	16, // 29: whatevr.v1.LoginService.Logout:output_type -> whatevr.v1.LogoutResponse
	18, // 30: whatevr.v1.ChatService.ListChats:output_type -> whatevr.v1.ListChatsResponse
	20, // 31: whatevr.v1.ChatService.GetMessages:output_type -> whatevr.v1.GetMessagesResponse
	22, // 32: whatevr.v1.ChatService.MarkChatRead:output_type -> whatevr.v1.MarkChatReadResponse
	24, // 33: whatevr.v1.SendService.SendText:output_type -> whatevr.v1.SendTextResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_whatevr_proto_init() }
func file_proto_whatevr_proto_init() {
	if File_proto_whatevr_proto != nil {
		return
	}
	file_proto_whatevr_proto_msgTypes[3].OneofWrappers = []any{
		(*DaemonEvent_ConnectionChanged)(nil),
		(*DaemonEvent_LoginStateChanged)(nil),
		(*DaemonEvent_NewMessage)(nil),
		(*DaemonEvent_MessageUpdated)(nil),
		(*DaemonEvent_ChatUpdated)(nil),
	}
	file_proto_whatevr_proto_msgTypes[10].OneofWrappers = []any{
		(*LoginEvent_QrCode)(nil),
		(*LoginEvent_LoginStateChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whatevr_proto_rawDesc), len(file_proto_whatevr_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_whatevr_proto_goTypes,
		DependencyIndexes: file_proto_whatevr_proto_depIdxs,
		EnumInfos:         file_proto_whatevr_proto_enumTypes,
		MessageInfos:      file_proto_whatevr_proto_msgTypes,
	}.Build()
	File_proto_whatevr_proto = out.File
	file_proto_whatevr_proto_goTypes = nil
	file_proto_whatevr_proto_depIdxs = nil
}
